gamefi/urls.py
from django.urls import path
from . import views

app_name = 'gamefi'

urlpatterns = [
    path("", views.home, name="home"),
]

gamifi/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import (LeaderboardListView, UserFriendsListView,ExerciseChoiceDetailView,ExerciseCreateView,ExerciseUpdateView)
from django.views.generic import TemplateView
app_name = 'gamifi'


urlpatterns = [
    path("", views.home, name="home"),
    path('activity_log/',views.activity_log,name="activity-log"),
    path('leaderboard/',LeaderboardListView.as_view(),name='leaderboard'),
    path('profile/<str:username>/', views.profile,name='profile'),
    path('editprofile/', views.edit_profile,name="edit-profile"),
    path('friends/',UserFriendsListView.as_view(),name='friends-list'),
    path('send_friend_request/<int:pk>/',views.send_friend_request,name="send-friend-request"),
    path('accept_friend_request/<int:pk>/',views.accept_friend_request,name="accept-friend-request"),
    path('deny_friend_request/<int:pk>/',views.deny_friend_request,name="deny-friend-request"),
    path('unfriend/<str:username>/',views.unfriend,name="unfriend"),
    path('catalog/',views.catalog,name= 'exercise-catalog'),
    path('exercise/<int:pk>/',ExerciseChoiceDetailView.as_view(),name= 'exercise-detail'),
    path('exercise/new/',ExerciseCreateView.as_view(),name= 'exercise-create'),
    path('exercise/new/<str:name>_<str:type>/',ExerciseCreateView.as_view(),name= 'exercise-create-preset'),
    path('exercise/update/<int:pk>/', ExerciseUpdateView.as_view(), name='exercise-update'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groupA10Site/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('', include('gamifi.urls')),
    path('gamifi/', include('gamifi.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view(),name="logout"),
]
#REFERENCED for logging in/out: https://whizzoe.medium.com/in-5-mins-set-up-google-login-to-sign-up-users-on-django-e71d5c38f5d5

gamifi/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import requests

# Create your models here.
#SOURCE: https://www.youtube.com/watch?v=FdVuKt_iuSI&list=PL-osiE80TeTtoQCKZ03TU5fNfx2UY6U4p&index=8
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    friends = models.ManyToManyField(User,related_name='friends',blank=True)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    experience = models.IntegerField(default=0)
    bio = models.TextField(blank=True)

    def __str__(self):
        return f'{self.user.username} Profile'

#SOURCE: https://medium.com/analytics-vidhya/add-friends-with-689a2fa4e41d
class FriendRequest(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE,related_name='receiver')

class Comment(models.Model):
    profile = models.ForeignKey(Profile,on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    body = models.TextField()
    created_on=models.DateTimeField(auto_now_add=True)

class Exercise(models.Model):
    url = "https://wger.de/api/v2/exerciseinfo/"
    url2 = "https://wger.de/api/v2/exercisecategory/" #endpoint for the exercise categories
    PARAMS = {'language': '2', 'limit': '300'} #2 = English
    headers = {'Accept': 'application/json', 'Authorization': 'Token 518ec96910a70e2731964b7899a2b2a52fd0feaf'}
    response = requests.get(url=url, headers=headers, params=PARAMS)
    response2 = requests.get(url=url2, headers=headers)
    exercises = response.json()["results"]
    categories=response2.json()["results"]
    NAME_CHOICES = [
                ('Running', 'RUNNING'),
                ('Swimming', 'SWIMMING'),
                ('Biking', 'BIKING'),
                ('Walking', 'WALKING')
            ]
    SUFFIX_CHOICES = [
            ('Repetitions', 'repetitions'),
            ('Minutes', 'minutes'),
            ('Hours', 'hours'),
            ('Laps', 'laps')
        ]
    CATEGORY_CHOICES = []
    for e in exercises:
        NAME_CHOICES.append((e["name"],e["name"]))
    for c in categories:
        CATEGORY_CHOICES.append((c['name'],c['name']))

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    finished = models.BooleanField(default=False)
    duration = models.PositiveSmallIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    category = models.CharField(max_length=50, choices = CATEGORY_CHOICES)
    name = models.CharField(max_length=50, choices=NAME_CHOICES)
    exp = models.IntegerField(default=100)
    duration_suffix = models.CharField(max_length=50, choices=SUFFIX_CHOICES)

    def get_absolute_url(self):
        return reverse('gamifi:activity-log')

class ExerciseChoice(models.Model):
    name = models.CharField(max_length=100, blank = True, null = True)
    description=models.TextField(blank = True, null = True)
    image_url=models.CharField(max_length=100,blank = True, null = True)
    category=models.CharField(max_length=20,blank = True, null = True)

gamifi/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile, Comment, Exercise

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image','bio']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['title','body']

class ExerciseForm(forms.ModelForm):
    class Meta:
        model = Exercise
        fields = ['name','duration','duration_suffix','category','finished']

gamifi/views.py
# Create your views here.

from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.db.models import Sum

from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .models import Exercise, User, Profile, FriendRequest, ExerciseChoice
from .forms import UserUpdateForm, ProfileUpdateForm, CommentForm, ExerciseForm
from itertools import chain
from django.contrib import messages
import requests
import re

def home(request):
    return render(request, 'gamifi/index.html')

@login_required
def catalog(request):
    #REFERENCED THIS SOURCE:  https://dev.to/yahaya_hk/how-to-populate-your-database-with-data-from-an-external-api-in-django-398i
    if (ExerciseChoice.objects.count()==0):
        url ="https://wger.de/api/v2/exerciseinfo/"
        PARAMS ={'language':'2','limit':'300'}
        headers = {'Accept': 'application/json','Authorization': 'Token 518ec96910a70e2731964b7899a2b2a52fd0feaf'}
        response = requests.get(url=url,headers=headers,params=PARAMS)
        exercises = response.json()["results"]

        #regex for filtering out html tags
        cleanr = re.compile('<.*?>')

        for e in exercises:
            desc = re.sub(cleanr, '', e['description'])
            if (len(e['images']) > 0):
                exercise_data = ExerciseChoice(
                    name=e['name'],
                    description=desc,
                    category=e['category']['name'],
                    image_url=e['images'][0]['image']
                )
            else:
                exercise_data = ExerciseChoice(
                    name=e['name'],
                    description=desc,
                    category=e['category']['name'],
                )

            exercise_data.save()

    all_exercises=ExerciseChoice.objects.all()
    context = {'exercises':all_exercises}
    return render(request,'gamifi/catalog.html',context)

class ExerciseChoiceDetailView(generic.DetailView):
    model = ExerciseChoice
    template_name = 'gamifi/exercise_detail.html'

@login_required
def send_friend_request(request, pk):
    sender = request.user
    receiver = User.objects.get(pk=pk)
    friend_request, created = FriendRequest.objects.get_or_create(sender=sender, receiver=receiver)
    if created:
        #messages.success(request, "friend request sent!")
        return redirect('gamifi:profile',username=request.user.username)
    else:
        #messages.ERROR(request, "friend request was already sent")
        return HttpResponse("already sent")


#https://medium.com/analytics-vidhya/add-friends-with-689a2fa4e41d , referenced for friend requests
@login_required
def accept_friend_request(request,pk):
    friend_request=FriendRequest.objects.get(pk=pk)
    if friend_request.receiver == request.user:
        friend_request.sender.profile.friends.add(request.user)
        friend_request.receiver.profile.friends.add(friend_request.sender)
        friend_request.delete()
        messages.success(request, "friend request accepted!")
        return redirect('gamifi:profile',username=request.user.username)
    else:
        return HttpResponse('friend request not accepted')

@login_required
def deny_friend_request(request,pk):
    friend_request=FriendRequest.objects.get(pk=pk)
    if friend_request.receiver == request.user:
        friend_request.delete()
        messages.success(request, "friend request denied!")
        return redirect('gamifi:profile',username=request.user.username)
    else:
        return HttpResponse('---------------')

@login_required
def unfriend(request,username):
   ex_friend=User.objects.get(username=username)

   #sever the bond. :(
   request.user.profile.friends.remove(ex_friend)
   ex_friend.profile.friends.remove(request.user)
   return redirect('gamifi:friends-list')

class UserFriendsListView(generic.ListView):
    model = User
    template_name = "gamifi/friends_list.html"

    def get_queryset(self):
        return self.request.user.profile.friends.all() #get all of the user's friends, in object_list
        #return User.objects.filter(profile__friends=self.request.user)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the friend requests sent to this user
        context['all_friend_requests'] = FriendRequest.objects.filter(receiver=self.request.user)
        return context

@login_required
def activity_log(request):
    #For every completed exercise, sum up exp
    exercise_total = Exercise.objects.filter(user=request.user, finished=True).aggregate(Sum('exp'))['exp__sum']

    #update exp total for user
    exp_total=sum(filter(None,[exercise_total]))
    Profile.objects.filter(user=request.user).update(experience=exp_total)

    exercise_list=Exercise.objects.filter(user=request.user)

    context = {'exercise_list':exercise_list,
               'exp_total':exp_total}
    return render(request, 'gamifi/activity_log.html',context)



#https://www.youtube.com/watch?v=UmljXZIypDc&list=PL-osiE80TeTtoQCKZ03TU5fNfx2UY6U4p, refereneced Corey Schafer django tutorial series for profile makign
@login_required
def profile(request,username):
    # 'usr' is who the profile being viewed belongs to. "user" in the template is the person viewing the page
    usr = User.objects.get(username=username)
    #handle commenting
    if request.method == 'POST':
        c_form = CommentForm(data=request.POST)
        if c_form.is_valid():
            new_comment= c_form.save(commit=False) #get the new comment
            new_comment.profile = usr.profile #tie it to the profile being commented on
            new_comment.save()
            return redirect('gamifi:profile',username=username)
    else:
        c_form=CommentForm()
    context = {
        'usr':usr,
        'friends': request.user.profile.friends.all(), #pass in a list of friends for the purpose of deciding what buttons appear on the page
        'c_form': c_form,
        'comments':usr.profile.comment_set.all()
    }
    return render(request, 'gamifi/profile.html', context)

@login_required
def edit_profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            return redirect('gamifi:profile',username=request.user.username)

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }

    return render(request, 'gamifi/edit_profile.html', context)

class ExerciseCreateView(generic.CreateView):
    form_class = ExerciseForm
    template_name = 'gamifi/exercise_form.html'

    #Prepopulate form with url parameters if given
    def get_initial(self):
        initial = super().get_initial()
        if('name' in self.kwargs and 'type' in self.kwargs):
            initial['name'] = self.kwargs['name']
            initial['category'] = self.kwargs['type']
        return initial

    def form_valid(self, form):
        #form=form(initial={'name': self.kwargs['name']})
        form.instance.user = self.request.user
        return super().form_valid(form)

class ExerciseUpdateView(generic.UpdateView):
    model = Exercise
    form_class = ExerciseForm
    template_name = 'gamifi/exercise_form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class LeaderboardListView(generic.ListView):
    model= User
    template_name = 'gamifi/leaderboard_list.html'
    #context_object_name is object_list
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)

        #return list of users with their total exp in their profile. pass it into context
        leaders = User.objects.annotate(total=Sum('profile__experience')).order_by('-total')
        context['user_list'] = leaders
        return context

gamifi/templates/gamifi/activity_log.html
{% extends "gamifi/base.html" %}
{%block content %}
{% load socialaccount %}


{% if user.is_authenticated %}


<h1 style="text-align:center" class="display-1">Activity Log</h1>
<h4 style="text-align:center" class="display-4">Your Current Experience: {{exp_total}} XP</h4>
<div style="text-align: center">
<a class="btn btn-outline-primary" href="{% url 'gamifi:exercise-create' %}">ADD AN EXERCISE</a>
<a class="btn btn-outline-primary" href="{% url 'gamifi:exercise-catalog' %}">ADD EXERCISE FROM CATALOG</a>
<!--{{exp_total}}-->
</div>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Type</th>
      <th scope="col">Duration</th>
      <th scope="col">Date Created</th>
      <th scope="col">Complete?</th>
    </tr>
  </thead>
  <tbody>
  {% for exercise in exercise_list %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td><a href="{% url 'gamifi:exercise-update' exercise.id %}">{{exercise.name}}</a></td>
      <td> {{exercise.category}}</td>
      <td>{{exercise.duration}} {{exercise.duration_suffix}}</td>
        <td>{{exercise.created_at}}</td>
      <td>{{exercise.finished}}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>

  {% else %}
  <div class="container">
    <div class="row" >
        <div class="col-lg-12 text-center">

            <h2 class="section-heading">We should place a catchy app name or slogan here!</h2>
            <hr class="primary" />
            <p>
                Text about the APP and what our goal is.I'm going to add a background image here but this a template for now. Lorem ipsum dolor sit amet,
                consectetur adipiscing elit. Praesent vitae dui lectus. In a
                dui elit. Suspendisse magna tortor, rutrum ut consectetur a,
                tempor eu nibh. Maecenas scelerisque turpis nunc, vel
                finibus dui facilisis ac. Nullam tincidunt purus ac ante
                rhoncus laoreet. Aenean mollis lorem ac quam imperdiet
                placerat. Sed vehicula orci et tincidunt sollicitudin. Sed
                quis placerat lorem. Aliquam at dolor eu nibh pretium
                ultricies id a ex. Fusce sollicitudin hendrerit neque id
                imperdiet. Fusce malesuada tempus ante non eleifend. Proin
                in euismod quam. Maecenas interdum vehicula augue ut
                volutpat. Fusce maximus purus vel est accumsan feugiat. Ut
                quam neque, dignissim sit amet elit viverra, molestie ornare
                nisi. Maecenas eget ex ornare, molestie dui eget, cursus
                nibh. Phasellus euismod ut velit sed scelerisque. Donec in
                suscipit nulla, faucibus cursus dui. Mauris quis porta nisl.
                Interdum et malesuada fames ac ante ipsum primis in
                faucibus. Pellentesque sapien orci, sollicitudin sed
                pharetra eu, fermentum sit amet sapien. Cras interdum semper
                justo ac aliquam. Nullam turpis tortor, tristique ac rhoncus
                et, tempus ac metus. Vestibulum ut dapibus augue, nec
                laoreet ligula. Maecenas eget turpis tellus. Integer sem
                nulla, consequat eget justo vel, imperdiet rhoncus lorem.
                Aliquam erat volutpat. Donec dapibus tempus consequat. Etiam
                placerat rhoncus euismod. Morbi sit amet varius est. Donec
                tincidunt metus elit, molestie fermentum libero pulvinar et.
                Integer fringilla turpis magna. Morbi tristique sed leo at
                scelerisque.

            </p>
        </div>

    </div>
</div>

  {% endif %}
{% endblock %}

gamifi/templates/gamifi/base.html
<!DOCTYPE html>
<html>
<head>  
    <title></title>
    {% load static %}
    {% load bootstrap4 %}
    <link rel="stylesheet" type="text/css" href="{% static 'gamifi/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
  {% load socialaccount %}

  <div>
  <nav class="navbar navbar-expand-sm navbar-transparent">
    <div class="navbar-collapse ">
      <ul class="navbar-nav mr-auto">
              <!--<a class="navbar-brand mb-0 h1 color-warning">Post-Covid Exercise Gamifi</a>-->
			  <img src="https://i.imgur.com/zRpRYNT.png" style="width:180px;height:72px;">
      </ul>
    </div>
  {% if user.is_authenticated %}
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
            <ul class="nav navbar-nav ml-auto">
              <li>
                <a class="nav-link " href="{%url 'gamifi:friends-list' %}">Friends</a>
              </li>
                <li>
                    <a class="nav-link " href="{%url 'gamifi:leaderboard' %}">Leaderboard</a>
                </li>
                <li>
                    <a class="nav-link " href="{%url 'gamifi:activity-log' %}">Activity Log</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'gamifi:profile' user.username %}">My Profile</a>
                </li>
                <li>
                <a class="nav-link" href="{% url 'logout' %}">Sign-Out</a>
              </li>
            </ul>
    </div>
  </nav>
  {% else %}
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
      <ul class="nav navbar-nav ml-auto">
          <li>
              <a class="nav-link" href="{% provider_login_url 'google' %}">Sign-In with Google</a>
          </li>
      </ul>
    </div>
  {% endif %}
  </div >
  </nav>
{% block content %}
{% endblock %}

</body>


</html>

gamifi/templates/gamifi/catalog.html
{% extends 'gamifi/base.html' %}
{% block content %}
	<h1 style="text-align:center" class="display-1">Exercise Catalog</h1>
  <div class = "container">
    <br><br>
    <div class="row">
      {% for e in exercises %}
        <div class="col-md-4 col-sm-6 col-lg-3">
          <div class="card">
            <img class="card-img-top" src="{{ e.image_url }}" alt="Card image cap" onError="this.onerror=null;this.src='https://i.imgur.com/zRpRYNT.png';">
            <div class="card-body text-center">
              <h5 class="card-title">{{ e.name }}</h5>
              <hr>
			  <p><u>Works the:</u></p>
              <p class="card-text">{{e.category }}</p>
              <a href="{% url 'gamifi:exercise-detail' e.id %}"
              ><input
                type="submit"
                value="Learn More"
                class="btn btn-outline-primary btn-sm"
                type="button"
            /></a>
            </div>
          </div>
          <br><br><br>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}
<!--https://dev.to/yahaya_hk/how-to-populate-your-database-with-data-from-an-external-api-in-django-398i-->

gamifi/templates/gamifi/choose_exercise.html
{% extends "gamifi/base.html" %}
{% load static %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm">
      <div class="card" style="width: 18rem;">
  <img src="{% static 'gamifi/images/cardio.png' %}" class="card-img-top" alt="aerobic">
  <div class="card-body">
    <h5 class="card-title">Aerobic Training</h5>
    <p class="card-text">Add aerobic exercises such as running, swimming...</p>
    <a href="{%url 'gamifi:aerobic-create' %}" class="btn btn-primary stretched-link">Add Exercise</a>
  </div>
</div>
    </div>
    <div class="col-sm">
      <div class="card" style="width: 18rem;">
  <img src="{% static 'gamifi/images/strength.png' %}" class="card-img-top" alt="strength">
  <div class="card-body">
    <h5 class="card-title">Strength Training</h5>
    <p class="card-text">Add strength exercises such as deadlifts, pushups...</p>
    <a href="{%url 'gamifi:strength-create' %}" class="btn btn-primary stretched-link">Add Exercise</a>
  </div>
</div>
    </div>
    <div class="col-sm">
      <div class="card" style="width: 18rem;">
  <img src="{% static 'gamifi/images/flexibility.png' %}" class="card-img-top" alt="flexibility">
  <div class="card-body">
    <h5 class="card-title">Flexibility Training</h5>
    <p class="card-text">Add flexibility exercises such as stretches</p>
    <a href="{%url 'gamifi:flexibility-create' %}" class="btn btn-primary stretched-link">Add Exercise</a>
  </div>
</div>
    </div>
  </div>
</div>




{% endblock content %}
<!--source https://getbootstrap.com/docs/4.4/utilities/stretched-link/ -->

gamifi/templates/gamifi/exercise_detail.html
{% extends "gamifi/base.html" %}
{%block content %}
<div class = "container">
    <br><br>
    <div class="row">
        <div class="col-md-5">
          <br>
          <img class="img-fluid" src="{{ object.image_url }}" alt="" style = "width: 90%;">
          <br><br>
          <h3 class="card-title text-center ">{{ object.name }}</h3>
        </div>
        <div class="col-md-7 shadow-lg p-3 mb-5 bg-white rounded">
          <h1 class="my-3">Exercise Description</h1>
          <p class = "lead">{{ object.description }}</p>
          <h1 class="my-3">Exercise Details</h1>
          <ul>
            <li>{{ object.category }}</li>
          </ul>
            <a class="btn btn-primary" href="{% url 'gamifi:exercise-create-preset' name=object.name type=object.category %}" role="button">Add Exercise</a>
        </div>
    </div>
</div>

{% endblock %}
<!--SOURCE: https://dev.to/yahaya_hk/how-to-populate-your-database-with-data-from-an-external-api-in-django-398i-->

gamifi/templates/gamifi/exercise_form.html
{% extends "gamifi/base.html" %}
{% load crispy_forms_tags %}
{%block content %}

<h1>Exercise Form</h1>
<div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Exercise Goal</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock %}

gamifi/templates/gamifi/friends_list.html
{% extends "gamifi/base.html" %}
{%block content %}
<div class = "container" style="text-align: center">
    <h1 class="display-1">Your Friends</h1>
    {% for friend in object_list %}
    <ul class="list-group">
        <li class="list-group-item"><a href="{% url 'gamifi:profile' friend.username %}">{{friend.username}}</a>
        <a href="{% url 'gamifi:unfriend' friend.username %}" class = "btn btn-danger">Unfriend</a></li>
    </ul>
    {% endfor %}
</div>

<div class = "container">
    <h4 class="display-4">Friend Requests</h4>
    {% for fr in all_friend_requests %}
    <ul class="list-group">
        <li class="list-group-item"><a href="{% url 'gamifi:profile' fr.sender.username %}">{{fr.sender}}</a>
            <a class="btn btn-primary" href="{% url 'gamifi:accept-friend-request' fr.id %}" role="button">Accept</a>
            <a class="btn btn-primary" href="{% url 'gamifi:deny-friend-request' fr.id %}" role="button">Deny</a></li>
    </ul>
    {% endfor %}
</div>

{% endblock %}

gamifi/templates/gamifi/profile.html
{% extends 'gamifi/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="media" style="justify-content: center">
		<img class="account-img rounded-circle" src="{{ usr.profile.image.url }}" style="width:165px;height:165px;" onError="this.onerror=null;this.src='http://zultimate.com/wp-content/uploads/2019/12/default-profile.png';">
		<div class="align-self-center">
			<h2 class="display-2">{{ usr.username }}</h2>
			<h5 class="display-5">{{ usr.email }}</h5>
		</div>
	</div>

		<div class="card mx-auto" style="text-align:center; width: 18rem;">
		  <div class="card-body">
			<h5 class="card-title display-7">About Me</h5>
			<p class="card-text">{{ usr.profile.bio }}</p>
		  </div>
		</div>
	
  {% for comment in comments %}
        <div class="comments" style="padding: 10px; text-align: center;">
          <p class="font-weight-bold">
            {{user.username}} commented on <span class=" text-muted font-weight-normal">
            {{ comment.created_on }}
          </span>:
		  </p>
		  <p>
			<u><em>Title: </em>{{ comment.title }}</u>
		  </p>
		  <div>
			{{ comment.body | linebreaks }}
		  </div>
		  
        </div>
        {% endfor %}

{% if user == usr %}
<div style="text-align: center">
<a class="btn btn-outline-primary mx-auto" href="{% url 'gamifi:edit-profile' %}" role="button">Edit Profile</a>
</div>
{% elif usr not in friends %}
<div style="text-align: center">
<a class="btn btn-outline-primary" href="{% url 'gamifi:send-friend-request' usr.id %}" role="button">Send Friend Request</a>
</div>
{% else %}
<h3>Leave a comment</h3>
        <form method="post" style="margin-top: 1.3em;">
			{% csrf_token %}
          {{ c_form|crispy }}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
{%endif%}
{% endblock content %}

<!--source https://djangocentral.com/creating-comments-system-with-django/ -->